export declare type Corporation = {
  'Card Name': string;
  'Card #': string;
  'Cost': string;
  'Card Type': 'Corporation';
  'Deck': 'Basic' | 'Corporate';
  'Req: Temperature': -30;
  'Req: Oxygen': 0;
  'Req: Ocean': 0;
  'Req: Venus': 0;
  'Req: Max Temperature': 8;
  'Req: Max Oxygen': 14;
  'Req: Max Ocean': 9;
  'Req: Max Venus': 30;
  'Pre-requisites (Global)': string;
  'Req: Science': 0;
  'Req: Building': 0;
  'Req: Space': 0;
  'Req: Microbe': 0;
  'Req: Plant': 0;
  'Req: Animal': 0;
  'Req: City': 0;
  'Req: Earth': 0;
  'Req: Jovian': 0;
  'Req: Energy': 0;
  'Req: Venus__1': 0;
  'Req: Other': 'No';
  'Pre-requisites (Non-Global)': string;
  'Tag: Science': number;
  'Tag: Building': number;
  'Tag: Space': number;
  'Tag: Microbe': number;
  'Tag: Plant': number;
  'Tag: Animal': number;
  'Tag: City': number;
  'Tag: Earth': number;
  'Tag: Jovian': number;
  'Tag: Energy': number;
  'Tag: Venus': number;
  'Tag: Event': number;
  'Tags': string;
  'Prod: Megacredit': number;
  'Prod: Steel': number;
  'Prod: Titanium': number;
  'Prod: Plant': number;
  'Prod: Energy': number;
  'Prod: Heat': number;
  'Production': string;
  'Inv: Megacredit': number;
  'Inv: Steel': 0 | 5 | 20;
  'Inv: Titanium': 0 | 10;
  'Inv: Plant': number;
  'Inv: Energy': 0;
  'Inv: Heat': 0;
  'Other (Resources on Cards)': 'No';
  'Resource': string;
  'Temperature': 0;
  'Oxygen': 0;
  'Ocean': 0;
  'Venus': 0;
  'TR': 0;
  'VP': 0;
  'Terraforming Effect': string;
  'Tile/Colony Placement': 'No' | 'Ref';
  '# Actions and/or Effect': 1 | 'Eff';
  'Depends on opponents': 'No';
  'Affects opponents': 'No';
  'Holds Resources': 'No';
  'Interactions': string;
  'Action or On-going Effect text': string;
  'One time Effect Text': string;
  'Text': string;
};
