codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "90...100"
  status:
    project:
      default:
        # basic
        target: 95%
    patch:
      default:
        # basic
        target: 90%
